apiVersion: pipes.services.k8s.aws/v1alpha1
kind: Pipe
metadata:
 name: ack-pipe
 namespace: team-b
spec:
  name: ack-pipe
  source: arn:aws:dynamodb:us-west-2:771174509839:table/ack-table/stream/2023-04-18T15:45:56.545
  sourceParameters:
    dynamoDBStreamParameters:
      startingPosition: LATEST
      batchSize: 10
      maximumRecordAgeInSeconds: 500
    filterCriteria:
      filters:
      - pattern: '{"eventName":["INSERT"]}'
  target: arn:aws:sqs:us-west-2:771174509839:ack-queue
  description: pipe create by ACK
  roleARN: arn:aws:iam::771174509839:role/ack-pipe-role
  tags:
    event: serverless-office-hours